### PR TITLE
add me as a collaborator in CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by RosoPenaranda**
**IMPORTANT: Please do not create a Pull Request without creating an issue first.**

## Fixed issues (PRs without this will not be accepted)
- Fixes #ISSUE_1
- Fixes #ISSUE_2

## Changes
- Change 1
- Change 2
- Change 3

## PR Checklist
- [ ] Does your PR contain relevant tests that pass?
- [ ] Is your code linted? `yarn lint` or `yarn lint:fix`
- [ ] Does your code build correctly in ALL projects? `yarn build`

### CODE REVIEW

**Review by tristanMatthias — CHANGES_REQUESTED** [review]
Hey @RosoPenaranda can you please add the month in as well 🙏

**Comment by RosoPenaranda** [comment]
issue  [#205](https://github.com/code-mentoring/learn/issues/205)
I solved the date, what else I have to do?

**Comment by quimgv** [comment]
Hey @RosoPenaranda I think the issue has to be added up above in the description like: 

Fixes #ISSUENUMBER

so that the issue gets linked to this PR and gets closed automatically when merged.

Also I think you are working on your forked repo, I think @tristanMatthias should give you access to contribute in the original one and just clone that one in your local machine.

**Comment by ahmedfaaid** [comment]
Hey @tristanMatthias @quimgv @RosoPenaranda should I edit this for Roso since I see the issue number in the issues list?

**Comment by tristanMatthias** [comment]
Sorry this took so long!

**Pull request merged**
