### PR TITLE
Feat/sign out api

### LINKED ISSUE #113: User signing out - API
## The story:

As a **signed-in user** that **wants to sign out**, I want to be able to **click on a button to sign out**.

---

## What we should do:
Build a sign-out mutation that clears the `accessToken` from the `LoginOutput` Type and return a message saying:

> You have signed out!

---

## To be successful we need to:

- [ ] Make a `signOut` query
- [ ] Redirect the signed-out user to the login page
- [ ] Return a boolean indicating if the user has signed out
- [ ] Contain relevant tests for work done that pass in CI

---

### Query: `signOut`
```gql
query {
  signOut # Returns a boolean
}
```
#115

### PR DESCRIPTION
**Pull request by lanphantastic**
**IMPORTANT: Please do not create a Pull Request without creating an issue first.**

## Fixed issues (PRs without this will not be accepted)
- Fixes #113 

## Changes
- sign out user returns a true boolean

## PR Checklist
- [x] Does your PR contain relevant tests that pass?
- [x] Is your code linted? `yarn lint` or `yarn lint:fix`
- [x] Does your code build correctly in ALL projects? `yarn build`

### CODE REVIEW

**Comment by tristanMatthias** [comment]
@lanphantastic, I can't update that file because it's on your fork. If you want to merge this in you gotta fix the schema.gql merge conflict first haha.

**Comment by ghost** [comment]
Hi @lanphantastic 

@tristanMatthias approved this PR 5 days ago but you need to resolve file conflicts before it can be merged.

Any update on this?

**Comment by ghost** [comment]
@lanphantastic Pinged you on Slack, I'm looking for back-end work myself so I can help or take over if you're busy.
Let me know.

**Comment by tristanMatthias** [comment]
I'm closing this as it's been almost 2 weeks and communication has been minimal. If we want to add real functionality to this with redis invalidation that would be good, otherwise I don't see this helping particularly atm.

**Pull request closed without merging**
