### PR TITLE
Feature/setup ci GitHub actions

### LINKED ISSUE #7: Setup CI - Github actions
**Is your feature request related to a problem? Please describe.**
Currently there is no CI to check PRs and new commits.

**Describe the solution you'd like**
Using Github actions, we should have an automated check that tests the API and front end, linting, seeding, etc for any new PR or commit

**Describe alternatives you've considered**
Travis could also work, but github actions seems to be the best solution considering our tasks are all here

### PR DESCRIPTION
**Pull request by shaneSheridan**
- Fixes #7
-  Disabled "linebreak-style" lint - there were many files failing on the Windows CI
- Added ci.yml for on push/PR CI actions
- Added "test" script to root
- Fixed some lint errors

### CODE REVIEW

**Comment by shane215** [comment]
Is "yarn install" enough, or does this require more commands?

**Comment by tristanMatthias** [comment]
We'll add to it as we go. Right now, it should test all packages. 
If you add a root level command (under the root `package.json`) with:
```
"test": "lerna run test"
```

And add that as a command as well.

**Comment by shaneSheridan** [comment]
Test script fails until we have an in memory test database.

`[Nest] 3319   - 04/24/2020, 2:38:34 PM   [ExceptionHandler] Unable to connect to the database. Retrying (1)...
Error: connect ECONNREFUSED 127.0.0.1:5432
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1107:14)`

**Comment by shaneSheridan** [comment]
@tristanMatthias Will we wait for the in-memory test database to be setup before merging this?

I think that we can merge this and just check that every PR passes all except "test".

**Pull request merged**
